configs:
  avahi-hosts:
    content: |
      skull.local = 192.168.10.17
      unifi.local = 192.168.10.9:wq

services:
  avahi-daemon:
    build: .
    container_name: avahi-daemon
    restart: unless-stopped
    configs:
      - source: avahi-hosts
        target: /etc/avahi/hosts
    environment:
      - AVAHI_HOST_NAME=avahi-daemon
    network_mode: host
