configs:
  avahi-hosts:
    content: |
      skull.local = 192.168.10.17
      unifi.local = 192.168.10.9
  avahi-config:
    content: |
      [server]
      host-name=avahi
      domain-name=local
      enable-dbus=no
      use-ipv6=no

services:
  avahi-daemon:
    build: .
    container_name: avahi-daemon
    restart: unless-stopped
    configs:
      - source: avahi-hosts
        target: /etc/avahi/hosts
      - source: avahi-config
        target: /etc/avahi/avahi-daemon.conf
    environment:
      - AVAHI_HOST_NAME=avahi-daemon
    network_mode: host
